site_name: Maestro
repo_url: https://github.com/topfreegames/maestro

nav:
  - Home: 'index.md'
  - UserGuides: 'User Guides.md'
  - Developers: 'Developers.md'
  - Architecture: 'Architecture.md'
  - OpenAPI: 'OpenAPI.md'
  - Operations: 'Operations.md'
  - Kubernetes Usage: 'Kubernetes.md'
  - Guidelines: 'Guidelines.md'


theme:
  name: material
  logo: https://github.com/topfreegames/maestro/blob/main/docs/images/gopher-maestro.png?raw=true
  palette:
    primary: cyan

plugins:
  - git-revision-date
  - search
  - render_swagger
  - mermaid2:
      version: 8.14.0
