{{- if eq .Values.global.database_location "on-cluster" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: maestro-postgres
  name: maestro-postgres
  annotations:
    "helm.sh/hook": pre-install
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: maestro-postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maestro-postgres
  labels:
    heritage: maestro-postgres
  annotations:
    "helm.sh/hook": pre-install
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maestro-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
        ports:
          - containerPort: 5432
        env:
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        - name: POSTGRES_USER
          value: maestro
        - name: POSTGRES_DB
          value: maestro
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP --username maestro
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP --username maestro
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
{{- end}}
