---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maestro-worker
  labels:
    heritage: maestro-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maestro-worker
    spec:
      volumes:
        - name: config
          configMap:
            name: maestro-cm
      containers:
        - name: maestro-worker
          command:
            - "/bin/sh"
            - "-c"
            - "/app/maestro worker --incluster"
          image: quay.io/tfgco/maestro:v{{ .Chart.Version }}
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /app/config/local.yaml
              subPath: local.yaml
          env:
            - name: MAESTRO_EXTENSIONS_PG_HOST
              value: {{ .Values.postgres_host }}
            - name: MAESTRO_EXTENSIONS_PG_PORT
              value: "{{ .Values.postgres_port }}"
            - name: MAESTRO_EXTENSIONS_PG_USER
              value: {{ .Values.postgres_user }}
            - name: MAESTRO_EXTENSIONS_PG_PASS
              value: {{ .Values.postgres_password }}
            - name: PGPASSWORD
              value: {{ .Values.postgres_password }}
            - name: MAESTRO_EXTENSIONS_PG_DATABASE
              value: {{ .Values.postgres_database }}
            - name: MAESTRO_EXTENSIONS_REDIS_URL
              value: {{ .Values.redis_url }}
            {{- if ne .Values.newrelic_app "" }}
            {{- if ne .Values.newrelic_key "" }}
            - name: MAESTRO_NEWRELIC_APP
              valueFrom:
                secretKeyRef:
                  name: maestro-secret
                  value: newrelicapp
            - name: MAESTRO_NEWRELIC_KEY
              valueFrom:
                secretKeyRef:
                  name: maestro-secret
                  value: newrelickey
            {{- end}}
            {{- end}}
