apiVersion: v1
kind: Service
metadata:
  name: maestro-api
spec:
  selector:
    app: maestro-api
  ports:
    - protocol: TCP
      port: 80
{{- if eq .Values.use_ingress "true" }}
  type: ClusterIP
{{- else}}
  type: LoadBalancer
{{- end}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maestro-api
  labels:
    heritage: maestro-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maestro-api
    spec:
      volumes:
        - name: config
          configMap:
            name: maestro-cm
      containers:
        - name: maestro-api
          command:
            - "/bin/sh"
            - "-c"
            - "/app/maestro migrate && /app/maestro start -p 80 --incluster"
          image: quay.io/tfgco/maestro:v{{ .Chart.Version }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /app/config/local.yaml
              subPath: local.yaml
          env:
            - name: MAESTRO_EXTENSIONS_PG_HOST
              value: {{ .Values.postgres_host }}
            - name: MAESTRO_EXTENSIONS_PG_PORT
              value: "{{ .Values.postgres_port }}"
            - name: MAESTRO_EXTENSIONS_PG_USER
              value: {{ .Values.postgres_user }}
            - name: MAESTRO_EXTENSIONS_PG_PASS
              value: {{ .Values.postgres_password }}
            - name: MAESTRO_RUN_SETUP
              value: "true"
            - name: MAESTRO_EXTENSIONS_PG_DATABASE
              value: {{ .Values.postgres_database }}
            - name: MAESTRO_GOOGLE_CLIENT_ID
              value: {{ .Values.google_clientid }}
            - name: MAESTRO_GOOGLE_CLIENT_SECRET
              value: {{ .Values.google_clientsecret }}
            - name: MAESTRO_OAUTH_ACCEPTEDDOMAINS
              value: {{ .Values.oauth_domains }}
            - name: MAESTRO_EXTENSIONS_REDIS_URL
              value: {{ .Values.redis_url }}
            - name: MAESTRO_BASICAUTH_USERNAME
              value: {{ .Values.basicauth_user }}
            - name: MAESTRO_BASICAUTH_PASSWORD
              value: {{ .Values.basicauth_pass }}
            - name: MAESTRO_BASICAUTH_TRYOAUTHIFUNSET
              value: "true"
            {{- if ne .Values.newrelic_app }}
            {{- if ne .Values.newrelic_key }}
            - name: MAESTRO_NEWRELIC_APP
              valueFrom:
                secretKeyRef:
                  name: maestro-secret
                  value: newrelicapp
            - name: MAESTRO_NEWRELIC_KEY
              valueFrom:
                secretKeyRef:
                  name: maestro-secret
                  value: newrelickey
            {{- end}}
            {{- end}}
