{
   "name": "scheduler-name",
   "game": "game-name",
   "image": "nginx:alpine",
   "ports": [
      {
         "containerPort": 8080,
         "protocol": "TCP",
         "name": "tcp"
      }
   ],
   "limits": {
      "memory": "128Mi",
      "cpu": "20m"
   },
   "shutdownTimeout": 10,
   "autoscaling": {
      "min": 2,
      "up": {
         "delta": 1,
         "trigger": {
            "usage": 70,
            "time": 1
         },
         "cooldown": 1
      },
      "down": {
         "delta": 1,
         "trigger": {
            "usage": 50,
            "time": 1
         },
         "cooldown": 1
      }
   }
}
