extensions:
  pg:
    host: "localhost"
    port: 8765
    user: "maestro"
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: "maestro"
    connectionTimeout: 100
  redis:
    url: redis://localhost:6363
    connectionTimeout: 200
watcher:
  autoScalingPeriod: 10
  lockKey: "maestro-lock-key"
  lockTimeoutMs: 180000
  gracefulShutdownTimeout: 300
worker:
  syncPeriod: 10
  gracefulShutdownTimeout: 300
scaleUpTimeoutSeconds: 300
deleteTimeoutSeconds: 150
pingTimeout: 30
sentry:
  url: ""
newrelic:
  app: "maestro"
  key: ""
