internalApi:
  port: 8082
  gracefulShutdownTimeout: 10s
  metrics:
    enabled: true
  healthcheck:
    enabled: true
adapters:
  schedulerStorage:
    postgres:
      url: "postgres://maestro:maestro@localhost:5432/maestro?sslmode=disable"
  operationFlow:
    redis:
      url: "redis://localhost:6379/0"
  operationStorage:
    redis:
      url: "redis://localhost:6379/0"
  operationLeaseStorage:
    redis:
      url: "redis://localhost:6379/0"
  runtime:
    kubernetes:
      inCluster: false
      masterUrl: "https://127.0.0.1:6443"
      kubeconfig: "./kubeconfig.yaml"
  portAllocator:
    random:
      range: 60001-60010
  roomStorage:
    redis:
      url: "redis://localhost:6379/0"
  instanceStorage:
    redis:
      url: "redis://localhost:6379/0"
  schedulerCache:
    redis:
      url: "redis://localhost:6379/0"
workers:
  syncInterval: 10s
  stopTimeoutDuration: 1m
services:
  roomManager:
    roomPingTimeoutMillis: 90000
    roomInitializationTimeoutMillis: 120000
    roomDeletionTimeoutMillis: 120000
  operationManager:
    operationLeaseTtlMillis: 5000
  eventsForwarder:
    schedulerCacheTtlMillis: 120000
