database_location: "on-cluster"
redis_location: "on-cluster"
use_ingress: "false"
postgres_host: maestro-postgres
postgres_port: "5432"
postgres_user: maestro
postgres_database: maestro
postgres_password: ""
redis_url: redis://:@maestro-redis:6379
google_clientid: ""
google_clientsecret: ""
oauth_domains: "example.com other.com"
tls_crt: ""
tls_key: ""
maestro_url: "maestro.example.com"
